### ISSUE TITLE
Can't install on MacOS Big Sur (11.0)

### ISSUE THREAD

**Issue by WiseOneChan** [deepcharles/ruptures#92]
I get the following error:

```Collecting ruptures
  Using cached ruptures-1.1.1.tar.gz (229 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/useruser/Desktop/scrooge/pytrends-master/.venv/bin/python3 /Users/useruser/Desktop/scrooge/pytrends-master/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/tmpku27q7pu
       cwd: /private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-install-isdzeylx/ruptures
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/Users/useruser/Desktop/scrooge/pytrends-master/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/useruser/Desktop/scrooge/pytrends-master/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/useruser/Desktop/scrooge/pytrends-master/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 73, in <module>
      ext_modules=cythonize(
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
      module_list, module_metadata = create_extension_list(
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/private/var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/pip-build-env-fjmx14v2/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'ruptures/detection/_detection/ekcpd.pyx' doesn't match any files
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/useruser/Desktop/scrooge/pytrends-master/.venv/bin/python3 /Users/useruser/Desktop/scrooge/pytrends-master/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/b9/zxn96m217ml71fhycn_xsvx00000gn/T/tmpku27q7pu Check the logs for full command output.
```

**Comment by deepcharles** [comment]
We fixed some bugs in the latest (not yet released) version. You can install it using:

```
python -m pip install ruptures==1.1.2rc1
```

Can you tell me if that works for you?

**Comment by deepcharles** [comment]
Closing for now, feel free to reopen.
